<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Ennemi;

class EnnemiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->command->info('Creating enemies...');

        $ennemis = [
            // PIRATES - Niveau 1-3
            [
                'code' => 'PIRATE_ECLAIREUR',
                'nom' => 'Eclaireur Pirate',
                'description' => 'Petit vaisseau pirate rapide mais fragile.',
                'type' => 'pirate',
                'faction' => 'independant',
                'niveau' => 1,
                'difficulte' => 'facile',
                'coque_max' => 50,
                'bouclier_max' => 20,
                'bouclier_regen' => 2,
                'esquive' => 20,
                'degats_min' => 3,
                'degats_max' => 8,
                'precision' => 65,
                'cadence' => 2,
                'type_arme' => 'laser',
                'resistance_laser' => 0,
                'resistance_canon' => 0,
                'resistance_missile' => 0,
                'resistance_plasma' => 0,
                'resistance_emp' => -10,
                'tactique' => 'fuite',
                'seuil_fuite' => 40,
                'credits_min' => 50,
                'credits_max' => 150,
                'xp_recompense' => 25,
                'zone_niveau_min' => 1,
                'zone_niveau_max' => 5,
                'chance_spawn' => 30,
            ],
            [
                'code' => 'PIRATE_CHASSEUR',
                'nom' => 'Chasseur Pirate',
                'description' => 'Vaisseau pirate standard, equilibre.',
                'type' => 'pirate',
                'faction' => 'independant',
                'niveau' => 2,
                'difficulte' => 'moyen',
                'coque_max' => 80,
                'bouclier_max' => 40,
                'bouclier_regen' => 3,
                'esquive' => 15,
                'degats_min' => 6,
                'degats_max' => 12,
                'precision' => 70,
                'cadence' => 2,
                'type_arme' => 'laser',
                'resistance_laser' => 5,
                'resistance_canon' => 5,
                'resistance_missile' => 0,
                'resistance_plasma' => 0,
                'resistance_emp' => -5,
                'tactique' => 'equilibre',
                'seuil_fuite' => 25,
                'credits_min' => 100,
                'credits_max' => 300,
                'xp_recompense' => 50,
                'zone_niveau_min' => 1,
                'zone_niveau_max' => 6,
                'chance_spawn' => 25,
            ],
            [
                'code' => 'PIRATE_MARAUDEUR',
                'nom' => 'Maraudeur Pirate',
                'description' => 'Vaisseau pirate lourd avec bon armement.',
                'type' => 'pirate',
                'faction' => 'cartel',
                'niveau' => 3,
                'difficulte' => 'moyen',
                'coque_max' => 120,
                'bouclier_max' => 60,
                'bouclier_regen' => 4,
                'esquive' => 10,
                'degats_min' => 10,
                'degats_max' => 20,
                'precision' => 75,
                'cadence' => 1,
                'type_arme' => 'canon',
                'resistance_laser' => 10,
                'resistance_canon' => 10,
                'resistance_missile' => 5,
                'resistance_plasma' => 0,
                'resistance_emp' => 0,
                'tactique' => 'agressif',
                'seuil_fuite' => 15,
                'credits_min' => 200,
                'credits_max' => 500,
                'xp_recompense' => 100,
                'zone_niveau_min' => 2,
                'zone_niveau_max' => 7,
                'chance_spawn' => 20,
            ],

            // DRONES - Niveau 1-4
            [
                'code' => 'DRONE_SENTINELLE',
                'nom' => 'Drone Sentinelle',
                'description' => 'Drone automatise de patrouille.',
                'type' => 'drone',
                'faction' => 'independant',
                'niveau' => 1,
                'difficulte' => 'facile',
                'coque_max' => 30,
                'bouclier_max' => 0,
                'bouclier_regen' => 0,
                'esquive' => 25,
                'degats_min' => 4,
                'degats_max' => 8,
                'precision' => 80,
                'cadence' => 3,
                'type_arme' => 'laser',
                'resistance_laser' => -10,
                'resistance_canon' => 10,
                'resistance_missile' => -20,
                'resistance_plasma' => -10,
                'resistance_emp' => -50,
                'tactique' => 'agressif',
                'seuil_fuite' => 0,
                'credits_min' => 30,
                'credits_max' => 80,
                'xp_recompense' => 20,
                'zone_niveau_min' => 1,
                'zone_niveau_max' => 4,
                'chance_spawn' => 25,
            ],
            [
                'code' => 'DRONE_COMBAT',
                'nom' => 'Drone de Combat',
                'description' => 'Drone militaire automatise.',
                'type' => 'drone',
                'faction' => 'empire',
                'niveau' => 3,
                'difficulte' => 'moyen',
                'coque_max' => 60,
                'bouclier_max' => 30,
                'bouclier_regen' => 5,
                'esquive' => 20,
                'degats_min' => 8,
                'degats_max' => 16,
                'precision' => 85,
                'cadence' => 2,
                'type_arme' => 'laser',
                'resistance_laser' => 0,
                'resistance_canon' => 15,
                'resistance_missile' => -10,
                'resistance_plasma' => 0,
                'resistance_emp' => -40,
                'tactique' => 'agressif',
                'seuil_fuite' => 0,
                'credits_min' => 80,
                'credits_max' => 200,
                'xp_recompense' => 60,
                'zone_niveau_min' => 2,
                'zone_niveau_max' => 6,
                'chance_spawn' => 15,
            ],

            // CONTREBANDIERS - Niveau 2-5
            [
                'code' => 'CONTREBANDIER_RAPIDE',
                'nom' => 'Coureur Contrebandier',
                'description' => 'Vaisseau rapide de contrebande.',
                'type' => 'contrebandier',
                'faction' => 'cartel',
                'niveau' => 2,
                'difficulte' => 'moyen',
                'coque_max' => 70,
                'bouclier_max' => 50,
                'bouclier_regen' => 5,
                'esquive' => 30,
                'degats_min' => 5,
                'degats_max' => 12,
                'precision' => 70,
                'cadence' => 2,
                'type_arme' => 'laser',
                'resistance_laser' => 5,
                'resistance_canon' => 0,
                'resistance_missile' => 0,
                'resistance_plasma' => 5,
                'resistance_emp' => -15,
                'tactique' => 'fuite',
                'seuil_fuite' => 50,
                'credits_min' => 150,
                'credits_max' => 400,
                'xp_recompense' => 75,
                'zone_niveau_min' => 2,
                'zone_niveau_max' => 7,
                'chance_spawn' => 15,
            ],

            // MERCENAIRES - Niveau 3-6
            [
                'code' => 'MERCENAIRE_VETERAN',
                'nom' => 'Mercenaire Veteran',
                'description' => 'Pilote mercenaire experimente.',
                'type' => 'mercenaire',
                'faction' => 'independant',
                'niveau' => 4,
                'difficulte' => 'difficile',
                'coque_max' => 150,
                'bouclier_max' => 100,
                'bouclier_regen' => 6,
                'esquive' => 15,
                'degats_min' => 15,
                'degats_max' => 30,
                'precision' => 80,
                'cadence' => 1,
                'type_arme' => 'canon',
                'resistance_laser' => 10,
                'resistance_canon' => 15,
                'resistance_missile' => 10,
                'resistance_plasma' => 5,
                'resistance_emp' => 5,
                'tactique' => 'equilibre',
                'seuil_fuite' => 20,
                'credits_min' => 400,
                'credits_max' => 800,
                'xp_recompense' => 150,
                'zone_niveau_min' => 3,
                'zone_niveau_max' => 8,
                'chance_spawn' => 10,
            ],
            [
                'code' => 'MERCENAIRE_ELITE',
                'nom' => 'Mercenaire Elite',
                'description' => 'Chasseur de primes redoutable.',
                'type' => 'mercenaire',
                'faction' => 'independant',
                'niveau' => 5,
                'difficulte' => 'difficile',
                'coque_max' => 200,
                'bouclier_max' => 150,
                'bouclier_regen' => 8,
                'esquive' => 20,
                'degats_min' => 20,
                'degats_max' => 40,
                'precision' => 85,
                'cadence' => 2,
                'type_arme' => 'missile',
                'resistance_laser' => 15,
                'resistance_canon' => 20,
                'resistance_missile' => 15,
                'resistance_plasma' => 10,
                'resistance_emp' => 10,
                'tactique' => 'agressif',
                'seuil_fuite' => 10,
                'credits_min' => 600,
                'credits_max' => 1200,
                'xp_recompense' => 250,
                'zone_niveau_min' => 4,
                'zone_niveau_max' => 10,
                'chance_spawn' => 8,
            ],

            // BOSS - Niveau 5+
            [
                'code' => 'BOSS_CAPITAINE_PIRATE',
                'nom' => 'Capitaine Scarface',
                'description' => 'Legendaire capitaine pirate, terreur des routes commerciales.',
                'type' => 'pirate',
                'faction' => 'cartel',
                'niveau' => 5,
                'difficulte' => 'boss',
                'coque_max' => 300,
                'bouclier_max' => 200,
                'bouclier_regen' => 10,
                'esquive' => 15,
                'degats_min' => 25,
                'degats_max' => 50,
                'precision' => 80,
                'cadence' => 2,
                'type_arme' => 'plasma',
                'resistance_laser' => 20,
                'resistance_canon' => 25,
                'resistance_missile' => 20,
                'resistance_plasma' => 30,
                'resistance_emp' => 15,
                'tactique' => 'agressif',
                'seuil_fuite' => 5,
                'credits_min' => 2000,
                'credits_max' => 5000,
                'xp_recompense' => 500,
                'zone_niveau_min' => 5,
                'zone_niveau_max' => 10,
                'chance_spawn' => 3,
            ],
            [
                'code' => 'BOSS_DRONE_NEXUS',
                'nom' => 'Nexus Prime',
                'description' => 'Intelligence artificielle de combat autonome.',
                'type' => 'drone',
                'faction' => 'alien',
                'niveau' => 6,
                'difficulte' => 'boss',
                'coque_max' => 250,
                'bouclier_max' => 300,
                'bouclier_regen' => 15,
                'esquive' => 25,
                'degats_min' => 15,
                'degats_max' => 35,
                'precision' => 90,
                'cadence' => 3,
                'type_arme' => 'emp',
                'resistance_laser' => 10,
                'resistance_canon' => 10,
                'resistance_missile' => 0,
                'resistance_plasma' => 20,
                'resistance_emp' => 50,
                'tactique' => 'defensif',
                'seuil_fuite' => 0,
                'credits_min' => 3000,
                'credits_max' => 7000,
                'xp_recompense' => 750,
                'zone_niveau_min' => 6,
                'zone_niveau_max' => 10,
                'chance_spawn' => 2,
            ],
        ];

        foreach ($ennemis as $data) {
            Ennemi::create($data);
        }

        $this->command->info(count($ennemis) . ' enemies created');
    }
}
